services:
  app:
    build: .
    container_name: monitor-reports-app
    expose:
      - "3001:3000" # Porta interna do container (fechada para o mundo externo)
    env_file:
      - .env.local
    restart: always
